"""Legacy shim — canonical implementation is in y_web.src.forum.service."""
from __future__ import annotations

from y_web.src.forum.service.data_classes import (  # noqa: F401
    ArticlePreview,
    FeedPage,
    FeedPost,
    PostStats,
    _article_payload,
    _strip_article_title_from_body,
)
from y_web.src.forum.service.formatters import (  # noqa: F401
    _article_summary_needs_enrichment,
    _author_agent_page_cache,
    _clock_config_cache,
    _fetch_and_cache_og_image,
    _format_display_time,
    _format_display_time_from_created_at,
    _format_round,
    _get_experiment_dir,
    _get_profile_pic,
    _is_agent_or_page_author,
    _media_type_from_url,
    _og_image_cache,
    _resolve_article,
    _resolve_experiment_clock,
    _resolve_image,
    _resolve_image_post,
    _shared_from,
    _upgrade_reddit_image_url,
    clean_reddit_formatting,
    extract_reddit_summary_image,
    extract_youtube_thumbnail,
)
from y_web.src.forum.service.queries import (  # noqa: F401
    _build_comment_payload,
    _build_feed_posts,
    _comment_count_subquery,
    _create_feed_post,
    _fetch_comment_map,
    _fetch_reaction_map,
    _fetch_share_map,
    _fetch_viewer_vote_map,
    _normalize_posts,
    _post_with_aggregates,
    _reaction_aggregates_subquery,
    _share_count_subquery,
    _viewer_vote_subquery,
    build_user_feed_posts,
    fetch_feed_page,
    fetch_thread,
    serialize_feed_posts,
)
