version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - ysocial
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network
    ports:
      - 80:80

  ysocial:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ysocial
    depends_on:
      - db
    volumes:
      - ./:/app/
    environment:
      - FLASK_APP=/app/y_social.py
      - DATABASE_URL=postgresql://ysocial_user:ysocial_pass@db:5432/ysocial_db
      # - LLM_BACKEND=ollama  # Default: ollama. Options: ollama, vllm
    networks:
      my-network:
        aliases:
          - ysocial
    ports:
      - 5001:5000  # Host port 5001 -> Container port 5000

    command: python /app/y_social.py --host 0.0.0.0 --port 5000 --db postgresql

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      PG_DBNAME: dashboard
      PG_USER: postgres
      PG_PASSWORD: password
      PG_DBNAME_DUMMY: dummy
    networks:
      - my-network
    ports:
      - 5432:5432  # Optional: expose port to host

volumes:
  pgdata:

networks:
  my-network:
