services:
    nginx:
        image: nginx:latest
        container_name: nginx
        depends_on:
            - ysocial
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - my-network
        ports:
            - 80:80

    ysocial:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: ysocial
        volumes:
            - ./:/app/
        environment:
            - FLASK_APP=/app/y_web.py
        networks:
            my-network:
                aliases:
                    - ysocial
        ports:
            - 5001:5000  # Host port 5001 -> Container port 5000

        command: python /app/y_web.py --host 0.0.0.0 --port 5000

networks:
    my-network:
