version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - ysocial
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network
    ports:
      - 80:80

  ysocial:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ysocial
    volumes:
      - ./:/app/
    environment:
      - FLASK_APP=/app/y_social.py
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      my-network:
        aliases:
          - ysocial
    ports:
      - 5001:5000  # Host port 5001 -> Container port 5000

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    runtime: nvidia

    command: python /app/y_social.py --host 0.0.0.0 --port 5000 --db postgresql

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      PG_DBNAME: dashboard
      PG_USER: postgres
      PG_PASSWORD: password
      PG_DBNAME_DUMMY: dummy
    networks:
      - my-network
    ports:
      - 5432:5432  # Optional: expose port for local debugging

volumes:
  pgdata:

networks:
  my-network:
