name: Format Code

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.py'

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install formatting tools
      run: |
        python -m pip install --upgrade pip
        pip install black isort
    
    - name: Sort imports with isort
      run: |
        isort .
    
    - name: Format code with black
      run: |
        black .
    
    - name: Check for changes
      id: verify_diff
      run: |
        git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
    
    - name: Commit and push changes
      if: steps.verify_diff.outputs.changed == 'true' && github.event_name == 'push'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git commit -m "Auto-format code with isort and black [skip ci]"
        git push
    
    - name: Check formatting for PRs
      if: steps.verify_diff.outputs.changed == 'true' && github.event_name == 'pull_request'
      run: |
        echo "::error::Code is not properly formatted. Please run 'isort .' and 'black .' locally."
        exit 1
